- id: downscale-notebook-images
  name: Downscale notebook images
  entry: hooks/downscale_images_in_notebooks.py
  language: python
  types: [jupyter]
  additional_dependencies: [nbformat>=5.10.4, pillow>=10.3.0]