[project]
name = "notebooks-pre-commit"
version = "0.1.0"
description = "A pre-commit hook for cleaning python notebooks."
requires-python = ">=3.9"

dependencies = [
    "nbformat>=5.10.4",
    "pillow>=10.3.0",
]
